### ISSUE TITLE
FR: Type checker/guesser

### ISSUE THREAD

**Issue by SecMyth** [bytebutcher/decoder-plus-plus#1]
Please implement a handler that tries to guess the format in the fields for:
URL encoding
Base64 encoding (check for Padding = at the end)
gzip (magic bytes 1F8B0800)
etc.

If a known format is recognized the tool should name it and with a simple click further decoding should be done automatically.

**Comment by bytebutcher** [comment]
Thanks for your feature request.
I've added a "Smart decode" button. Currently only Base32, Base64, Hex (int), Hex(shell), Hex (str) are recognized. This was done by introducing a method "can_decode_input" for each "DecoderPlugin". 

When the "Smart decode" button is pressed each decoder-plugin is checked whether it "can_decode_input". This is usually done by using some kind of regex but each DecoderPlugin is able to implement its own behaviour. 

There is a bit more to this story. Just check out the _smart_decode_button_click_event method in codec_frame.py and the plugins (e.g. plugins/base32_decoder.py) for more information.
