### ISSUE TITLE
Feature Request - HTTP64

### ISSUE THREAD

**Issue by SecMyth** [bytebutcher/decoder-plus-plus#2]
Besides Base64 the variant HTTP64 could be supported. Similar to ftp://196.0.4.20/usr/appserver/usr-share/lib/jato/doc/api/com/iplanet/jato/util/Http64Decoder.html

**Comment by bytebutcher** [comment]
>  This class decodes characters that were previously encoded using a variant of Base64 encoding.  This encoding results in an encoded string that doesn't need to be escaped for use in HTTP URLs. Specifically, the following characters are remapped in this implementation:
```
 Location  Base64  Http64
 --------  ------  ------
   62        +       -
   63        /       _
  (pad)      =       $

``` 
When i understand correctly this looks like a simple remapping of base64. Should be quite easy to implement. I will add the plugin shortly.
