### ISSUE TITLE
error in kali linux

### ISSUE THREAD

**Issue by Darkcast** [bytebutcher/decoder-plus-plus#26]
<img width="649" alt="Screen Shot 2020-11-04 at 7 46 32 AM" src="https://user-images.githubusercontent.com/1676655/98113642-f70e9d80-1e71-11eb-9467-52fda00f4569.png">
I added path export PATH=$PATH/home/kali/.local/bin/
didnt work.

I am runnig tha latest version of kali 
I have zsh installed

**Comment by bytebutcher** [comment]
Hey there!
have you installed Decoder++ using pip3?
```
pip3 install decoder-plus-plus
```
If you haven't and you want to run from source you might try the following.

Instead of runnig dpp directly use the runner:
```
ln -s /path/to/dpp/runner.py /home/kali/.local/bin/dpp
```
or
```
python3 /path/to/dpp/runner.py
```
Hope this helps!

**Comment by bytebutcher** [comment]
Please feel free to reopen this ticket if the issue persists!
