### ISSUE TITLE
Support for BASE64URL

### ISSUE THREAD

**Issue by SecMyth** [bytebutcher/decoder-plus-plus#28]
I'd really like a support for [URL-safe Base64](http://tools.ietf.org/html/rfc4648).

I had the impression, DPP already supports this, if even via plugin. But could find it.

**Comment by bytebutcher** [comment]
Hey there, thanks for your report. I've added the url-safe base64 variant as suggested! You can either pull the new version from the repository or update dpp using pip. If you experience any problems please let me know!
